[Mono.Options] Improve error message for badly bundled args.
mono(1) supports a "joined" verbose flag, `mono -v-v-v-v`, which
Mono.Options doesn't support. Attempting to use it, however, resulted
in a "weird" error message:

	$ csharp -r:Mono.Options.dll
	csharp> using Mono.Options;
	csharp> var p = new OptionSet { { "v", v => {} } };
	csharp> p.Parse (new[]{"-v-v-v"});
	Mono.Options.OptionException: Cannot bundle unregistered option '--'.
	...

This looks very weird to users because they never used a "--" option,
and if they had then `--` would have disabled further option
processing (as documented and implemented in OptionSet.Parse()).

Confusion all around.

Improve the error message so that it instead generates:

	Mono.Options.OptionException: Cannot use unregistered option '-' in bundle '-v-v-v'.

That way the user gets the full context of where this "unregistered
option" came from.